config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users
  
  resources :albums do
  	resources :photos
  end	

  resources :users
  root 'dashboard#index'
end

app/models/album.rb
class Album < ApplicationRecord
	has_many :photos
	belongs_to :user

	validates :name, presence: true
	validates :name, length: { message: 'should have minimum 6 characters', minimum: 6 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :album, counter_cache: true

	has_attached_file :image, styles: { medium: "300x300>" , large: "600x600>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	validates :tagline, presence: true
	validates :image, presence: true
	validates :tagline , length: {message: 'should have minimum 6 characters' , minimum: 6}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

	def show
		@album = Album.find(params[:id])
		@photos = @album.photos.all
	end
	def new
		if user_signed_in? 
			@album = Album.new	

		else
			redirect_to root_path, notice: 'Please Login to access this page'
		end
		
	end

	def create
		album_param = album_params
		album_param[:user_id] = current_user.id
		@album = Album.new(album_param)


		if @album.save
			redirect_to  album_path(@album.id), notice: 'Album Successfully Created'

		else
			redirect_to action: 'new' 
			flash[:danger] = "Album was not created due to:#{@album.errors.full_messages}"
			
		end
		
	end

	private

		def album_params
			params.require(:album).permit(:name)
			
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@photos = Photo.all.order('created_at desc').limit(25)
  end

  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


	def new
		@album = Album.find(params[:album_id])
		@photo = Photo.new	
	end

	def create
		photo_param = photo_params
		photo_param[:album_id] = params[:album_id]
		@album = Album.find(params[:album_id])
		@photo = @album.photos.new(photo_param)
		
		if @album.photos_count > 24
			redirect_to album_path(@album.id)
			flash[:danger] = "Album cannot have more than 25 photos"
		else
			if @photo.save
				redirect_to album_path(@album.id), notice: 'Photo Successfully Added'
			else
				redirect_to album_path(@album.id)
				flash[:danger] = "Album was not created due to:#{@photo.errors.full_messages}"
			end	
		end
	end

	private
		def photo_params
			params.require(:photo).permit(:tagline, :album_id, :image)	
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@albums = @user.albums.order('created_at desc')

  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, html: {class: 'form-horizontal'} do |f| %>
	
	<div class="form-group">
		<%= f.label :name , class: 'col-sm-2 control-label' %></br>
		<div class="col-sm-10">
			<%= f.text_field :name, class: 'form-control', placeholder: 'Enter Album Name' %>
		</div>
	</div>


	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit "Save", class: 'btn btn-success' %>
		</div>
	</div>
	
<% end %>

app/views/albums/new.html.erb
<div class ="container">
	<ol class = "breadcrumb">
		<%= link_to "Home", root_path %>
		<center><b>Create New Album</b></center>
	</ol>

	<%= render 'form' %>
	
</div>
	

app/views/albums/show.html.erb
<div class ="container">
	<ol class = "breadcrumb">
		<%= link_to "Home", root_path %>|
		<%= link_to "Back to all Albums", user_path(@album.user_id) %>
		<% if user_signed_in? %>
			<center><b>Add Photos For The Album: "<%= @album.name%>" </b></center>
		<% else %>
			<center><b>Photos For The Album: "<%= @album.name%>"</b></center>
		<% end %>	
		<center><h4>This album contains <%= pluralize(@album.photos_count,'photo') %></h4><center>
	</ol>
	
	
	<% if user_signed_in? %>
		<% if @album.user_id == current_user.id %>
			<%= render 'photos/form' %>
		<% end %>
	<% end %>
	
	<% @photos.each do |photo|%>
		<center><p><h4>Photo Tag:<%= photo.tagline %></h4></p></center>
		<center><%= image_tag photo.image.url(:medium) %></center>
		<hr>
	<% end %>		
</div>

app/views/dashboard/index.html.erb
<div class ="container" >
	<ol class = "breadcrumb">
		<% if user_signed_in? %>
			<%= link_to "Create Album", new_album_path %>|
			<%= link_to "My Albums", user_path(current_user.id) %>
		<% end %>
		<center><b>Welcome to Image-Share Homepage</b></center>
	</ol>

	<p>
		<% @photos.each do |photo| %>
			<h4>Photo Tag: <%= photo.tagline %></h4>
			<h6>By:<%= link_to  photo.album.user.email , user_path(photo.album.user_id) %></h6>
			<center><%= image_tag photo.image.url(:medium) %></center>
			
			<hr>
		<% end %>
	</p>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageShare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class ="container" >
	  	<% if user_signed_in? %>
			Signed in as <%= current_user.email %> |
			<%= link_to "Sign out" , destroy_user_session_path, method: 'delete' %>

			<% else %>
				<%= link_to "Sign Up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %>
	  	<% end %>

	  	<% flash.each do |k,v| %>
			<div class="alert alert-success" role="alert"><center><%= v %></center> </div>
	  	<% end %>
	</div>

    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for ([@album, @album.photos.build]) , html: {class: 'form-horizontal', multipart: true } do |f| %>
	
	<div class="form-group">
		<%= f.label :image , class: 'col-sm-2 control-label' %></br>
		<div class="col-sm-10">
			<%= f.file_field :image %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :tagline, class: 'col-sm-2 control-label' %></br>
		<div class="col-sm-8">
			<%= f.text_field :tagline , class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit "Add Photos", class: 'btn btn-success' %>
		</div>
	</div>
	
<% end %>

app/views/photos/new.html.erb
<div class ="container">
	<ol class = "breadcrumb">
		<center><b>Add Photos</b></center>
	</ol>

	<%= render 'form' %>
	
</div>
	

app/views/users/show.html.erb
<div class ="container" >
	<ol class = "breadcrumb">
		<%= link_to "Home", root_path %>
		<% if user_signed_in? %>
			|<%= link_to "Create Album", new_album_path %>
		<% end %>
		<center><b>Album list for user <%= @user.email %></b></center>
		<center>click on the album name to view the album</center>
	</ol>
	<p>
		<% @albums.each do |album| %>
			<h4><%=link_to album.name, album_path(album.id) %></h4>

			<hr>
		<% end %>
	</p>

</div>